### ISSUE TITLE
Play store link dead

### ISSUE THREAD

**Issue by AGIsmail** [nominalista/expenses#5]
Hi there,

Thanks for the great app! 

Just wanted to let you know that the play store link seems to be dead:
https://play.google.com/store/apps/details?id=com.nominalista.expenses

**Comment by nominalista** [comment]
Hi, thanks for letting me know. I've already received e-mail from Google Play that this app has been removed due to lack of Privacy Policy. I've included such document and I'm waiting for the update.

**Comment by nominalista** [comment]
It's back.
